 # Project definitions
Task: Test-Joe-2019-10-16
scorer: Joe
date: Oct16

# Data paths
data_path: C:\Users\Can\Projects\CINPLA\DeepCage\examples\Test-Joe-2019-10-16\labeled-data
calibration_path: C:\Users\Can\Projects\CINPLA\DeepCage\examples\Test-Joe-2019-10-16\calibration-images
results_path: C:\Users\Can\Projects\CINPLA\DeepCage\examples\Test-Joe-2019-10-16\analysis_results
# Project paths
project_config: C:\Users\Can\Projects\CINPLA\DeepCage\examples\Test-Joe-2019-10-16
dlc_project_config: ''
dlc3d_project_configs: {}
